title: Lumbridge Crow
description: <a href="./index.md">Home Page</a> | <a href="./test.md">Page 1</a> | <a href="./index.md">Page 2</a><script src="./include.js"></script>
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
github:
  is_project_page: false
