title: Lumbridge Crow
description: <a href="./index">Home Page</a> | <a href="./test">Page 1</a> | <a href="./index">Page 2</a><script src="./include.js"></script>
remote_theme: remote_theme: vsoch/mkdocs-jekyll
plugins:
  - jekyll-remote-theme
github:
  is_project_page: false
