title: Lumbridge Crow
description: <a href="">Home Page</a> | <a href="">Page 1</a> | <a href="">Page 2</a><script src="./include.js"></script>
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
github:
  is_project_page: false
defaults:
  -
    scope:
      path: ""
    values:
      css: "./theme.css"
